### ISSUE TITLE
Timeseries data , Output interpretation

### ISSUE THREAD

**Issue by nsankar** [cslab-hub/multiSyncPy#12]
@travisjwiltshire @HleinaD  Thanks for developing this great library and excellent documentation in the paper.

The question I have is 

1. Can we use time series data where the sampling intervals are discontinous (i.e. having irregular sample time stamps)
2. In the paper , you have mentioned for Symbolic entropy, **Low values** of entropy are considered
indicative of behavior synchronized around some shared, regular and ordered pattern.  How do we interpret the values for high or level of synchronism for others viz., RHO, Coherence, Normalized CSD ?

Thanks in advance.

**Comment by travisjwiltshire** [comment]
Hi @nsankar! 

1. In principle, you could apply the methods to time series with discontinuous sampling intervals, but you'd have to think carefully about what that means for your data. Most people are looking for example for concurrent or time lagged synchrony, and having irregular sampled intervals would make that difficult to interpret. If the set of variables are irregularly sampled and sampled differently, I'm not really sure what kind of interpretation you could make.

2. For all of the metrics except entropy, the larger the value the more synchronized or temporally coordinated the multivariate time series are. But, we recommend comparing these values to see if they are higher than a surrogate baseline. 

Hope this helps!

**Comment by nsankar** [comment]
@travisjwiltshire  Appreciate your response. Thanks.
